import type { CrewMemberDetail } from "@/app/interfaces/CrewInterface";

export const MOCK_CREW: CrewMemberDetail[] = [
  {
    id: "cr_001",
    name: "Sarah Mitchell",
    email: "sarah.mitchell@prisma.example",
    phone: "+44 7700 901001",
    is_active: true,
    is_verified: true,
    headline: "Lead detailer · London & East",
    date_joined: "14 Jun 2023",
    lifetime_earnings: 84250.75,
    average_rating: 4.9,
    total_ratings: 412,
    total_bookings: 891,
    bio: "10+ years mobile detailing. IGER-certified, eco products on request.",
    specialties: ["Ceramic coating", "Interior deep clean", "Paint correction"],
    service_areas: ["E1–E18", "EC1", "Shoreditch"],
    vehicle_types: ["SUV", "Saloon", "Estate", "EV"],
    comments: [
      {
        id: "c1",
        created_at: "8 Mar 2025",
        text: "Exceptional finish on our Tesla. On time and professional.",
        author_label: "Customer",
        source: "customer",
        rating: 5,
      },
      {
        id: "c2",
        created_at: "1 Mar 2025",
        text: "Flagged for mentor programme — strong NPS trend this quarter.",
        author_label: "Support · Alex",
        source: "support",
      },
    ],
  },
  {
    id: "cr_002",
    name: "David Osei",
    email: "david.osei@prisma.example",
    phone: "+44 7700 901002",
    is_active: true,
    is_verified: false,
    headline: "Field coordinator · South London",
    date_joined: "22 Jan 2025",
    lifetime_earnings: 12840.0,
    average_rating: 4.6,
    total_ratings: 38,
    total_bookings: 72,
    bio: "Former fleet ops. Coordinating multi-van days and quality checks.",
    specialties: ["Fleet scheduling", "Quality audit"],
    service_areas: ["CR", "BR", "SE"],
    vehicle_types: ["Van", "SUV", "Commercial"],
    comments: [
      {
        id: "c3",
        created_at: "12 Mar 2025",
        text: "Documents uploaded — awaiting final ID verification.",
        author_label: "Support · Ops",
        source: "support",
      },
    ],
  },
  {
    id: "cr_003",
    name: "Priya Shah",
    email: "priya.shah@prisma.example",
    phone: "+44 7700 901005",
    is_active: false,
    is_verified: true,
    headline: "Detailer · Reading & Thames Valley",
    date_joined: "3 Sep 2022",
    lifetime_earnings: 62400.2,
    average_rating: 4.8,
    total_ratings: 256,
    total_bookings: 503,
    bio: "On seasonal leave. Pet-hair and fabric specialist.",
    specialties: ["Fabric shampoo", "Odour treatment"],
    service_areas: ["RG", "SL", "HP"],
    vehicle_types: ["Hatchback", "SUV", "MPV"],
    comments: [
      {
        id: "c4",
        created_at: "28 Feb 2025",
        text: "Account deactivated at crew request — return date TBC.",
        author_label: "Support",
        source: "support",
      },
      {
        id: "c5",
        created_at: "15 Feb 2025",
        text: "Best interior clean we’ve had. Booked again.",
        author_label: "Customer",
        source: "customer",
        rating: 5,
      },
    ],
  },
  {
    id: "cr_004",
    name: "Marcus Webb",
    email: "marcus.webb@prisma.example",
    phone: "+44 7700 901006",
    is_active: false,
    is_verified: false,
    headline: "Operations · Manchester",
    date_joined: "10 Nov 2024",
    lifetime_earnings: 2100.0,
    average_rating: 4.2,
    total_ratings: 6,
    total_bookings: 11,
    bio: "New joiner — onboarding paused pending references.",
    specialties: ["Exterior valet"],
    service_areas: ["M1–M20"],
    vehicle_types: ["Saloon", "SUV"],
    comments: [
      {
        id: "c6",
        created_at: "5 Mar 2025",
        text: "References not returned — follow up with applicant.",
        author_label: "Support · HR",
        source: "support",
      },
    ],
  },
];

export function getCrewById(id: string): CrewMemberDetail | undefined {
  return MOCK_CREW.find((c) => c.id === id);
}
