# Generated by Django 6.0.8 on 2026-08-19 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewChatThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crew_user_id', models.UUIDField(db_index=True, help_text='Detailer User.id (crew member)', unique=True)),
                ('crew_name', models.CharField(max_length=255)),
                ('crew_email', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('last_message_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('crew_unread_count', models.IntegerField(default=0, help_text="Messages from support that crew hasn't seen")),
                ('support_unread_count', models.IntegerField(default=0, help_text="Messages from crew that support hasn't seen")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crew_chat_threads',
                'ordering': ['-last_message_at'],
                'indexes': [models.Index(fields=['status', '-last_message_at'], name='idx_crew_chat_status_time')],
            },
        ),
        migrations.CreateModel(
            name='CrewChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_role', models.CharField(choices=[('crew', 'Crew'), ('support', 'Support'), ('system', 'System')], max_length=20)),
                ('sender_id', models.UUIDField(help_text='User.id (crew) or SupportStaff.id (support)')),
                ('sender_name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('booking_reference', models.CharField(blank=True, help_text='Optional booking ref mentioned in this message', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.crewchatthread')),
            ],
            options={
                'db_table': 'crew_chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['thread', 'created_at'], name='idx_crew_chat_thread_time')],
            },
        ),
    ]
